server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由ID，没有固定的规则，但是要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
#            - After=2021-04-20T14:10:31.635+01:00[Europe/London]  #在该时间点之后才能访问
#            - Before=2021-04-20T14:10:31.635+01:00[Europe/London]  #在该时间点之前才能访问
#            - Between=2021-04-20T14:10:31.635+01:00[Europe/London],2021-04-20T18:10:31.635+01:00[Europe/London]  #在两个时间点中间段才能访问
#            - Cookie=username,carl   #带指定的Cookie访问，格式为属性名+正则表达式，可以在cmd使用curl+网址测试 (curl http://localhost:9527/payment/lb  --cookie "username=carl")
#            - Header=X-Request-Id,\d+  #请求头要有X-RequestId属性并且值为整数的正则表达式，同样使用curl测试 (curl http://localhost:9527/payment/lb -H "X-Request-Id:123")
#            - Host ...
#            - Method=GET   #方法为GET时才能访问
#            - Query ...

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
