server:
  port: 80

# 服务别名---注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.134.137:2181,192.168.134.137:2182,192.168.134.137:2183